name = "synapt-events"
main = "index.js"
compatibility_date = "2024-09-23"

[[d1_databases]]
binding = "EVENTS_DB"
database_name = "synapt-events-db"
database_id = "25c5e283-cf2e-4d2c-a954-b6eba025bdc9"

