name: Rollback synapthub with bindings
on:
  workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: npm install -g wrangler
      - name: Deploy with D1 binding
        env:
          CLOUDFLARE_EMAIL: ${{ secrets.CF_EMAIL }}
          CLOUDFLARE_API_KEY: ${{ secrets.CF_KEY }}
        run: |
          wrangler deploy --config wrangler_synapthub.toml --no-bundle
